import { StyleSheet } from 'react-native';
import { colors } from '@/src/shared/constants/colors';
import { glassActionSurface } from './components';

export const batchStyles = StyleSheet.create({
  blProductHeader: {
    flexDirection: 'row' as const,
    justifyContent: 'space-between' as const,
    alignItems: 'center' as const,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
  },
  blProductName: { fontSize: 15, fontWeight: '700' as const, color: '#111', flex: 1 },
  blColHeader: {
    paddingHorizontal: 16,
    paddingTop: 4,
    paddingBottom: 4,
    fontSize: 30,
    color: '#666',
    fontWeight: '500' as const,
  },
  blRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    paddingHorizontal: 16,
    paddingVertical: 5,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#E5E5E5',
  },
  blDateText: { flex: 1, fontSize: 25, color: '#111' },
  blWarnIcon: { marginRight: 6 },
  blBtnGroup: { flexDirection: 'row' as const, gap: 8, marginRight: 12 },
  blAdjBtn: {
    ...glassActionSurface,
    width: 52,
    height: 52,
    borderRadius: 20,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  blWeightText: {
    fontSize: 25,
    fontWeight: '500' as const,
    color: 'white',
    width: 140,
    textAlign: 'right' as const,
  },
  blEmpty: { padding: 16, color: '#888', textAlign: 'center' as const },
  blFooter: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'space-between' as const,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderTopWidth: 1,
    borderTopColor: '#E0E0E0',
  },
  blValmisBtn: {
    ...glassActionSurface,
    borderRadius: 50,
    paddingHorizontal: 28,
    paddingVertical: 12,
  },
  blValmisBtnText: {
    color: colors.textOnDark,
    fontWeight: '700' as const,
    fontSize: 15,
  },
  blTotalText: { fontSize: 14, fontWeight: '700' as const, color: '#111', letterSpacing: 0.5 },
  blTotalRow: {
    flexDirection: 'row' as const,
    justifyContent: 'space-between' as const,
    alignItems: 'center' as const,
    paddingHorizontal: 20,
    paddingVertical: 12,
  },
  blTotalLabel: {
    fontFamily: 'Montserrat_600SemiBold',
    fontSize: 16,
    color: 'rgba(255,255,255,0.85)',
    letterSpacing: 1,
  },
  blTotalValue: {
    fontFamily: 'Montserrat_600SemiBold',
    fontSize: 20,
    color: '#FFFFFF',
  },
  blArchiveHeader: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'space-between' as const,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.12)',
  },
  blArchiveHeaderText: {
    fontFamily: 'Montserrat_500Medium',
    fontSize: 14,
    color: 'rgba(255,255,255,0.5)',
    letterSpacing: 1,
  },
  blArchiveRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    paddingHorizontal: 16,
    paddingVertical: 10,
    gap: 8,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: 'rgba(255,255,255,0.07)',
  },
  blArchiveLabel: {
    fontFamily: 'Montserrat_400Regular',
    fontSize: 18,
    color: 'rgba(255,255,255,0.55)',
  },
  blArchiveSub: {
    fontFamily: 'Montserrat_400Regular',
    fontSize: 12,
    color: 'rgba(255,255,255,0.3)',
    marginTop: 2,
  },
  blArchiveWeight: {
    fontFamily: 'Montserrat_400Regular',
    fontSize: 18,
    color: 'rgba(255,255,255,0.4)',
  },
});
